modLoader="javafml" #mandatory
loaderVersion="[36.2.0,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL="https://github.com/kmfisk/ZAWAFacilityConstruction/issues" #optional

[[mods]] #mandatory
    modId="zfc" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="ZAWA: Facility Construction" #mandatory
    #updateJSONURL="https://change.me.example.invalid/updates.json" #optional
    #displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
    logoFile="logo.png" #optional
    credits="fisk, Mnesikos" #optional
    authors="fisk, Mnesikos" #optional
    description='''
'''

[[dependencies.zfc]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36.2.20,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.zfc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.zfc]]
    modId="zawa"
    mandatory=true
    versionRange="[1.16.5-1.0.2-BeefBeta-TropicalExpedition3,)"
    ordering="AFTER"
    side="BOTH"
